library(e1071)
library(rpart)
library(caret)
train_ds<-read.csv('C:/Users/Administrator.WIN-DDMH8A5C2L8/Dropbox (Instant Analytics)/AWS ML Data/train.csv')
train_ds<-train_ds[-1]
train_ds$Day_of_Week <- gsub('Sunday',1, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Monday',2, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Tuesday',3, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Wednesday',4, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Thursday',5, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Friday',6, train_ds$Day_of_Week)
train_ds$Day_of_Week <- gsub('Saturday',7, train_ds$Day_of_Week)
train_ds$interest_level <- gsub('low',1, train_ds$interest_level)
train_ds$interest_level <- gsub('medium',2, train_ds$interest_level)
train_ds$interest_level <- gsub('high',3, train_ds$interest_level)

train_ds$hour<-as.factor(train_ds$hour)
train_ds$Day_of_Week<-as.factor(train_ds$Day_of_Week)
train_ds$bathrooms<-as.factor(train_ds$bathrooms)
train_ds$bedrooms<-as.factor(train_ds$bedrooms)
train_ds$ac<-as.factor(train_ds$ac)
train_ds$balcony<-as.factor(train_ds$balcony)
train_ds$common_space<-as.factor(train_ds$common_space)
train_ds$dishwasher<-as.factor(train_ds$dishwasher)
train_ds$doorman<-as.factor(train_ds$doorman)
train_ds$elevator<-as.factor(train_ds$elevator)
train_ds$fee<-as.factor(train_ds$fee)
train_ds$fireplace<-as.factor(train_ds$fireplace)
train_ds$gym<-as.factor(train_ds$gym)
train_ds$hardwood<-as.factor(train_ds$hardwood)
train_ds$laundry<-as.factor(train_ds$laundry)
train_ds$luxury<-as.factor(train_ds$luxury)
train_ds$parking<-as.factor(train_ds$parking)
train_ds$pets<-as.factor(train_ds$pets)
train_ds$playroom<-as.factor(train_ds$playroom)
train_ds$pool<-as.factor(train_ds$pool)
train_ds$pre_war<-as.factor(train_ds$pre_war)
train_ds$subway<-as.factor(train_ds$subway)
train_ds$interest_level<-as.factor(train_ds$interest_level)

#Used for Parameter Testing and Model Validation
smp_size <- floor(0.70 * nrow(train_ds))
train_ind <- sample(seq_len(nrow(train_ds)), size = smp_size)
trainset <- train_ds[train_ind,]
testset<- train_ds[-train_ind,]
svm.model <- svm(interest_level ~ ., data = trainset, kernel='radial',cost=100)
svm.pred <- predict(svm.model, testset[,-27])
table(pred = svm.pred, true = testset[,27])
confusionMatrix(testset$interest_level,svm.pred)

#Used for Developing Final Model and Ensemble Ready Output
svm.model <- svm(interest_level ~ ., data = train_ds, kernel='radial',cost=100,probability=TRUE)
svm.pred <- predict(svm.model, train_ds[,-27], probability = TRUE)